### ISSUE TITLE
Knock Off should not be able to knock off Mega Stones or cause extra damage

### ISSUE THREAD

**Issue by Aeliko** [BluRosie/hg-engine#187]
![knock_off](https://github.com/BluRosie/hg-engine/assets/47219799/a6dc397a-b579-40fc-9f29-3102c2ec8830)

**Comment by Aeliko** [comment]
[https://bulbapedia.bulbagarden.net/wiki/Knock_Off_(move)](https://bulbapedia.bulbagarden.net/wiki/Knock_Off_(move))
## Knock Off
### Generation V

Knock Off now removes the held item rather than rendering it unusable; this means that the Pokémon can obtain another item if its held item is removed by Knock Off. However, [Recycle](https://bulbapedia.bulbagarden.net/wiki/Recycle_(move)) still cannot recover an item removed by Knock Off.
...

And other stuff, so it needs modernisation

**Comment by BluRosie** [comment]
Knock Off now removes the held item rather than rendering it unusable; this means that the Pokémon can obtain another item if its held item is removed by Knock Off. However, [Recycle](https://bulbapedia.bulbagarden.net/wiki/Recycle_(move)) still cannot recover an item removed by Knock Off.

Wild Pokémon cannot remove held items of the player's Pokémon.

If the user faints due to the target's Ability ([Rough Skin](https://bulbapedia.bulbagarden.net/wiki/Rough_Skin_(Ability)) or [Iron Barbs](https://bulbapedia.bulbagarden.net/wiki/Iron_Barbs_(Ability))) or held [Rocky Helmet](https://bulbapedia.bulbagarden.net/wiki/Rocky_Helmet), it cannot remove the target's held item. However, Knock Off will still remove the target's held item if the user faints due to its own held [Life Orb](https://bulbapedia.bulbagarden.net/wiki/Life_Orb). If Knock Off causes a Pokémon with the [Sticky Hold](https://bulbapedia.bulbagarden.net/wiki/Sticky_Hold_(Ability)) Ability to faint, it can now remove that Pokémon's held item.

Knock Off can now remove a held Griseous Orb from any Pokémon other than [Giratina](https://bulbapedia.bulbagarden.net/wiki/Giratina_(Pok%C3%A9mon)). Knock Off cannot remove a [Plate](https://bulbapedia.bulbagarden.net/wiki/Plate) if the target is [Arceus](https://bulbapedia.bulbagarden.net/wiki/Arceus_(Pok%C3%A9mon)) (Multitype has no effect on Knock Off), and cannot remove a [Drive](https://bulbapedia.bulbagarden.net/wiki/Drive) if the target is [Genesect](https://bulbapedia.bulbagarden.net/wiki/Genesect_(Pok%C3%A9mon)). If those Pokémon use Knock Off on a target holding this item (whenever or not the target benefits from holding the item), the item will not be removed.

Knock Off's [power](https://bulbapedia.bulbagarden.net/wiki/Power) has been increased from 20 to 65.

Knock Off cannot remove a [Z-Crystal](https://bulbapedia.bulbagarden.net/wiki/Z-Crystal) from any Pokémon, a [Mega Stone](https://bulbapedia.bulbagarden.net/wiki/Mega_Stone) or [Orb](https://bulbapedia.bulbagarden.net/wiki/Colored_orbs) if the target could use it to [Mega Evolve](https://bulbapedia.bulbagarden.net/wiki/Mega_Evolution) or undergo [Primal Reversion](https://bulbapedia.bulbagarden.net/wiki/Primal_Reversion), a [memory](https://bulbapedia.bulbagarden.net/wiki/Memory) if the target is [Silvally](https://bulbapedia.bulbagarden.net/wiki/Silvally_(Pok%C3%A9mon)), a [Rusted Sword](https://bulbapedia.bulbagarden.net/wiki/Rusted_Sword) from [Zacian](https://bulbapedia.bulbagarden.net/wiki/Zacian_(Pok%C3%A9mon)), a [Rusted Shield](https://bulbapedia.bulbagarden.net/wiki/Rusted_Shield) from [Zamazenta](https://bulbapedia.bulbagarden.net/wiki/Zamazenta_(Pok%C3%A9mon)), or a [Booster Energy](https://bulbapedia.bulbagarden.net/wiki/Booster_Energy) from any [Paradox Pokémon](https://bulbapedia.bulbagarden.net/wiki/Paradox_Pok%C3%A9mon) (excluding [Koraidon](https://bulbapedia.bulbagarden.net/wiki/Koraidon_(Pok%C3%A9mon)) and [Miraidon](https://bulbapedia.bulbagarden.net/wiki/Miraidon_(Pok%C3%A9mon))), even if it hasn't consumed the item because its Ability triggered from the appropriate weather or terrain condition instead.

If Knock Off is used on a Pokémon that is holding an item that can be knocked off, its base power will be boosted by 50%. Knock Off cannot remove the held item of a target that has [Sticky Hold](https://bulbapedia.bulbagarden.net/wiki/Sticky_Hold_(Ability)) or if it hits the target's [substitute](https://bulbapedia.bulbagarden.net/wiki/Substitute_(move)), but the bonus damage will apply anyway. If used on a Pokémon weak to Dark-type moves holding a [Colbur Berry](https://bulbapedia.bulbagarden.net/wiki/Colbur_Berry), the Colbur Berry will still be eaten, but Knock Off will get the damage boost regardless. If used on a Pokémon that cannot lose its held item — such as a Pokémon holding its corresponding [Mega Stone](https://bulbapedia.bulbagarden.net/wiki/Mega_Stone) — this move will not receive the boost. Additionally, the boost will also not be applied if the user of Knock Off targets a Pokémon holding an item that would not be able to be removed from it.
