### ISSUE TITLE
roar brings in a bad egg

### ISSUE THREAD

**Issue by BluRosie** [BluRosie/hg-engine#19]
roar seems to just corrupt everything

**Comment by Drayano60** [comment]
I think this is happening because if `trywhirlwind` rolls a fail, it doesn't set what Pokemon should be brought in next but then the the new script forces the game to do it anyway

I dunno how to modify `trywhirlwind` itself but I managed to do a bit of a bodge fix here by just calling `trywhirlwind` over and over until it rolls a success, with some additional checks for cases where the switch can't happen:
https://github.com/Drayano60/hg-engine/pull/4/commits/cfb515263547af0f729e8e81b86bb172515ab280#diff-e1335e8298a138b962f9179c9f3f0f462bf93b5fa0236f0cc7bb3affd08e73b9R12

**Comment by BluRosie** [comment]
thanks for fixing this dray!
